server:
  port: 8076

spring:
  application:
    name: dna-admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portal
    username: vtw
    password: vtw123#
  data:
    web:
      pageable:
        default-page-size: 10
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-handlers-package: com.vtw.dna.common.mybatis.typehandlers
  type-aliases-package: com.vtw.dna.common.mybatis.typehandlers
logging:
  level:
    root: debug

