server:
  port: 8076

spring:
  application:
    name: dna-admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portal
    username: vtw
    password: vtw123#
  data:
    web:
      pageable:
        default-page-size: 10
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: DNA-IDE-INSTANCE
            instanceName: DnaAdminScheduler
          jobStore:
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 1000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            quartzDataSource:
              provider: hikaricp
              driver: ${spring.datasource.driver-class-name}
              URL: ${spring.datasource.url}
              user: ${spring.datasource.username}
              password: ${spring.datasource.password}
    auto-startup: false
  shell:
    interactive:
      enabled: true
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-handlers-package: com.vtw.dna.common.mybatis.typehandlers
  type-aliases-package: com.vtw.dna.common.mybatis.typehandlers
logging:
  level:
    root: info

